### ISSUE TITLE
error reading 2017 matlab. Sekoju tavām instrukcijām readme failā. ja kaut ko nesaprotu apskaidro mani ...

### ISSUE THREAD

**Issue by agroshvillis** [lv-csbg/vizan-client-matlab#4]
server = initVizAnLocalServer
Initialising VizAn Local REST Server...
Starting local server...

server = 

  localServer with properties:

    status: 0
    cmdout: 'Recreating docker_server_webapp_1 ... ←↵[1A[2K←Recreating docker_server_webapp_1 ... [32mdone[0m←[1BRecreating docker_server_webserver_1 ... ←↵[1A[2K←Recreating docker_server_webserver_1 ... [32mdone[0m←[1B'

>> res1 = visualise('model.json','model_map.svg','fba_result.svg', 'FBA');
Error using visualiseInR2016b (line 4)
modelFile was not found.

Error in visualise (line 21)
    response = visualiseInR2016b(p.Results.modelFile, p.Results.svgFile, p.Results.outputFile,
    p.Results.analysisType, p.Results.url, p.Results.show);

**Comment by rudolfspetrovs** [comment]
This is an example, not to be taken literally, but to show the meaning. Did you rename the model file to "model.json" and model map file to "model_map.svg'? Use the 2nd example if you did not rename files.
